### ISSUE TITLE
您好，在运行grf环境时需要的train_grf.py在文件中没有找到，请问可以补充上这部分代码吗，谢谢！

### ISSUE THREAD

**Issue by carrot0117** [xihuai18/A2PO-ICLR2023#2]

**Comment by xihuai18** [comment]
论文里的grf 11v11 实验是用当时还在开发的 https://github.com/jidiai/GRF_MARL 写的，如果你要跑11v11的话可以看看这个库。

---

The grf 11v11 experiment in the paper was written using https://github.com/jidiai/GRF_MARL which was still under development at the time. If you want to run 11v11, you can take a look at this library.
